# Generated by Django 4.2.17 on 2025-02-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_42_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='http://localhost:8000/public/kawai_voltali.jpg', upload_to='profile_images'),
        ),
    ]
