# Generated by Django 4.2.17 on 2025-02-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='public/kawai_voltali.jpg', upload_to='profile_images'),
        ),
    ]
