# Generated by Django 4.2.17 on 2025-02-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
