version: '3.8'

services:
  frontend:
    container_name: frontend_container
    build: ./front
    ports:
      - "8000:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html
  
  auth_service:
    container_name: auth_service_container
    build: ./back/auth_service
    ports:
      - "8001:8001"
    env_file:
      - ./back/auth_service/.env
    volumes:
      - ./back/auth_service:/app
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:13
    env_file:
      - ./back/auth_service/.env
    ports:
      - "5432:5432"
    volumes:
      - ./back/auth_service/db:/var/lib/postgresql/data

volumes:
  postgres_data: