version: '3.8'

services:
  frontend:
    container_name: frontend_container
    build: ./front
    ports:
      - "8000:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html
  
  auth_service:
    container_name: auth_service_container
    build: ./back/auth_service
    ports:
      - "8001:8001"
    env_file:
      - ./back/auth_service/.env
    volumes:
      - ./back/auth_service:/app
    depends_on:
      db:
        condition: service_healthy
          
  db:
    container_name: db_container
    build: ./back/db
    env_file:
      - ./back/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: