POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "username": "zack2", "password": "pass123" }

###

POST http://127.0.0.1:8001/signup/
Content-Type: application/json

{ "username": "zack2", "password": "pass123", "email": "new@gmail.com" }

###
 
GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Njg4MTAyLCJpYXQiOjE3MzY2ODc4MDIsImp0aSI6IjM3MWRjOTQzOWJjZTQzNjNiMDZlMjI5NTYzZjUyNTliIiwidXNlcl9pZCI6M30.ZQ4_X3Z4s3a7rItbUmjKCjaCdwt239yl93OxS4QR9iQ


###

### OAuth2 Login
GET http://localhost:8001/oauth2/login/


### OAuth2 Callback
GET http://localhost:8000/oauth2/callback/?code=c7b8c591a7b15f275c45db979e9ff852bb45a31d25ea117e655eaa1250d38efb
