POST http://127.0.0.1:8001/login/
Content-Type: application/json

{ "username": "zack2", "password": "pass123" }

###

POST http://127.0.0.1:8001/signup/
Content-Type: application/json

{ "username": "zack2", "password": "pass123", "email": "new@gmail.com" }

###
 
GET http://127.0.0.1:8001/test_token/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzQ0NDEwLCJpYXQiOjE3Mzc3NDQxMTAsImp0aSI6ImNiOTA0YThjZDI3NDRhMjA4ZTQ4YjJlM2M3ZjhjNjM4IiwidXNlcl9pZCI6Mn0.riTgcs4BcBeToqMYzUYF7Zc1dhkTop3kPpYs2-w7o6k


###

### OAuth2 Login
GET http://localhost:8001/oauth2/login/


### OAuth2 Callback
GET http://localhost:8001/oauth2/callback/?code=f29f22f3d43b86a301bf5f85641c85017c9d77c8fc03a414a55866875594c45a
