# Generated by Django 5.1.4 on 2024-12-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
