# Generated by Django 5.1.5 on 2025-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.PositiveIntegerField()),
                ('recipient', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('should_send', models.BooleanField(default=True)),
            ],
        ),
    ]
