# Generated by Django 5.1.4 on 2025-03-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='default_score_to_win',
            new_name='score_to_win',
        ),
    ]
