# Generated by Django 5.1.4 on 2025-03-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplayer',
            name='userevent_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
